version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  spring-app:
    image: ghcr.io/joerob25/sem-coursework-be:release
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/world?createDatabaseIfNotExist=true
    depends_on:
      - mysqldb

  angular-fe:
    image: joerob25/sem-coursework-fe:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - spring-app