name: Workflow for Integration tests

on:
  push:
    branches:
      - develop

jobs:
  build-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Package with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests=true package
      - name: Compose Docker containers
        run: docker compose up -d
      - name: Docker down
        run: docker compose down

#  integration-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up jdk 19
#        uses: actions/setup-java@v3
#        with:
#          java-version: '19'
#          distribution: 'temurin'
#      - name: Maven Integration Test
#        run: mvn --batch-mode --update-snapshots clean verify