name: Workflow for unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up jdk 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Run Maven Unit Test
        run: mvn --batch-mode --update-snapshots clean test